# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(783, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.network_info = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.network_info.setFont(font)
        self.network_info.setText("")
        self.network_info.setObjectName("network_info")
        self.gridLayout.addWidget(self.network_info, 0, 1, 1, 3)
        self.google_scholar_info = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.google_scholar_info.setFont(font)
        self.google_scholar_info.setText("")
        self.google_scholar_info.setObjectName("google_scholar_info")
        self.gridLayout.addWidget(self.google_scholar_info, 1, 1, 1, 3)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 3, 1, 1)
        self.paper_name = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.paper_name.setFont(font)
        self.paper_name.setObjectName("paper_name")
        self.gridLayout.addWidget(self.paper_name, 7, 0, 1, 3)
        self.determine = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.determine.setFont(font)
        self.determine.setObjectName("determine")
        self.gridLayout.addWidget(self.determine, 8, 0, 1, 2)
        self.network = QtWidgets.QHBoxLayout()
        self.network.setContentsMargins(11, 11, 11, 11)
        self.network.setObjectName("network")
        self.gridLayout.addLayout(self.network, 0, 0, 1, 1)
        self.bib_form = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.bib_form.setFont(font)
        self.bib_form.setObjectName("bib_form")
        self.gridLayout.addWidget(self.bib_form, 7, 3, 2, 1)
        self.google_scholar = QtWidgets.QHBoxLayout()
        self.google_scholar.setContentsMargins(11, 11, 11, 11)
        self.google_scholar.setObjectName("google_scholar")
        self.gridLayout.addLayout(self.google_scholar, 1, 0, 1, 1)
        self.recheck = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.recheck.setFont(font)
        self.recheck.setObjectName("recheck")
        self.gridLayout.addWidget(self.recheck, 3, 0, 1, 1)
        self.check_finish = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.check_finish.setFont(font)
        self.check_finish.setText("")
        self.check_finish.setObjectName("check_finish")
        self.gridLayout.addWidget(self.check_finish, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 6, 0, 1, 3)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(13)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 8, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 783, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.clear_save_bib = QtWidgets.QAction(MainWindow)
        self.clear_save_bib.setObjectName("clear_save_bib")
        self.open_save_bib = QtWidgets.QAction(MainWindow)
        self.open_save_bib.setObjectName("open_save_bib")
        self.menu.addAction(self.open_save_bib)
        self.menu.addAction(self.action)
        self.menu.addAction(self.clear_save_bib)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "bib格式或国标 GB/T 7714"))
        self.determine.setText(_translate("MainWindow", "确定"))
        self.recheck.setText(_translate("MainWindow", "重新检查"))
        self.label.setText(_translate("MainWindow", "文献全名"))
        self.comboBox.setItemText(0, _translate("MainWindow", "bib格式"))
        self.comboBox.setItemText(1, _translate("MainWindow", "国标GB/T 7714"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.action.setText(_translate("MainWindow", "设置"))
        self.clear_save_bib.setText(_translate("MainWindow", "清除缓存"))
        self.open_save_bib.setText(_translate("MainWindow", "打开"))

